using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SphereController : MonoBehaviour
{
    public float frictionCoefficient = 0.15f; // Coeficiente de fricci贸n
    private Rigidbody rb;

    void Start()
    {
        rb = GetComponent<Rigidbody>();
        rb.drag = frictionCoefficient; // Establece el coeficiente de fricci贸n como la resistencia al aire del Rigidbody
    }

    void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.CompareTag("Suelo")) // Si colisiona con un objeto con la etiqueta "Plane"
        {
            // Calcula la fuerza de fricci贸n
            Vector3 friction = -rb.velocity.normalized * frictionCoefficient * rb.mass * Physics.gravity.magnitude;
            rb.AddForce(friction); // Aplica la fuerza de fricci贸n al Rigidbody
        }
    }
}

